n = str(input('Digite o seu nome completo: ')).strip()
nome = n.split()
print(' MUito prazer em te conhecer !')
print('O seu primero nome é {}'.format(nome[0]))
print('O seu último nome é {}'.format(nome[len(nome)-1]))
